fixtures:
  repositories:
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "1ffd72d"
    rvm:
      repo: "git://github.com/swelther/puppet-rvm.git"
      ref: "14ba89f"
  symlinks:
    apache: "#{source_dir}/../apache"
    logrotate: "#{source_dir}/../logrotate"
    packages: "#{source_dir}/../packages"
